[project]
name = "2025-espresso-water"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apax[cuda]>=0.12.2",
    "ipsuite>=0.2.7",
    "ipykernel>=6.30.1",
    "jax[cuda12]==0.6.1",
]
