n_epochs: 10_000
patience: 500
data_parallel: true
data:

  dataset:
    processing: cached

  batch_size: 1
  valid_batch_size: 40

metrics:
  - name: energy
    reductions: [mae]
  - name: forces
    reductions: [mae]

loss:
  - name: energy
    loss_type: nll
    weight: 1.
    atoms_exponent: 1
  - name: forces
    loss_type: nll
    weight: 2.
    atoms_exponent: 1

model:
  name: gmnn
  basis:
    name: bessel
    n_basis: 16
    r_max: 5.5

  n_radial: 6

  nn:
  - 128
  - 128

  ensemble:
    kind: shallow
    n_members: 16

  calc_stress: false
  use_ntk: false
  b_init: zeros
  w_init: lecun
  scale_shift_dtype: fp64
  descriptor_dtype: fp32
  readout_dtype: fp32

callbacks:
- name: csv

optimizer:
  name: adamw
  emb_lr:   0.0001
  nn_lr:    0.0001
  scale_lr: 0.0001
  shift_lr: 0.0001
  rep_scale_lr: 0.0001
  rep_prefactor_lr: 0.0001
  gradient_clipping: 10.0

  kwargs:
    weight_decay: 0.0002
    b1: 0.85
    b2: 0.99

  schedule:
    name: cyclic_cosine
    period: 50
    decay_factor: 0.96
